name: lantern
description: Cloud Firestore's data structure definition language and code generator. Lantern lights bright future of your project.
version: 0.0.2
homepage: https://github.com/kikuchy/lantern
author: kikuchy <kikuchy.h@gmail.com>

executables:
  lantern: main

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  petitparser: ^2.4.0
  code_builder: ^3.2.0
  dart_style: ^1.3.3
  args: ^1.5.2
  collection: ^1.14.12

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
