name: lantern
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: kikuchy <kikuchy.h@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  petitparser: ^2.4.0
  code_builder: ^3.2.0
  dart_style: ^1.3.3
  args: ^1.5.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
